apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - name: http
      port: 80
      targetPort: 80   # 👈 change this from 8080 to 80
      nodePort: 30080

